Neovici/cosmoz-grouped-list

.gitignore
.travis.yml
cosmoz-grouped-list-template.html
cosmoz-grouped-list.js
demo/detach_test.html
demo/full-demo.html
demo/iron-list-test.html
demo/list-demo-behavior.html
demo/perf.html
demo/scroller-test.html
item-template.html
package-lock.json
package.json
polymer.json
test/.eslintrc
wct.conf.json

Add package.json, bower postinstall, travis-ci , polymer lint and test and eslint config

Improve component setup

---

.eslintrc.json
cosmoz-grouped-list.js
demo/basic.html
demo/detach_test.html
demo/full-demo.html
demo/index.html
demo/iron-list-test.html
demo/list-demo-behavior.html
demo/perf.html
demo/scroller-test.html
package-lock.json
test/.eslintrc
test/basic.html

Add basic item creation and select/deselect tests

Add basic tests

---

.editorconfig
.eslintrc.json
package-lock.json
package.json
test/basic.html

Formatted, key sorted , tab indented .eslintrc
Updated packages

Improve ESlint

---

.eslintrc.json
cosmoz-grouped-list-template.html
cosmoz-grouped-list.js
demo/full-demo.html

See https://github.com/Neovici/cosmoz-omnitable/issues/10
See PR https://github.com/Neovici/cosmoz-omnitable/pull/49

Add support for highlighted rows

---

.codeclimate.yml
.eslintrc.json
cosmoz-grouped-list-template.html
cosmoz-grouped-list.js
package.json
yarn.lock

Fix path forwarding with compatibility between V1 and V2
Required also in omnitable

Fix path forwarding with compatibility between V1 and V2

---

.codeclimate.yml
.eslintignore
.gitignore
.travis.yml
analysis.json
cosmoz-grouped-list-template-selector.html
cosmoz-grouped-list-template.html
cosmoz-grouped-list.js
demo/helpers/demo-full.html
package.json
test/basic.html
wct.conf.json
yarn.lock

fixes https://github.com/Neovici/cosmoz-grouped-list/issues/12

Tests code coverage and codeclimate config v2

---

.eslintrc.json
cosmoz-grouped-list-template.html
cosmoz-grouped-list.js
demo/helpers/demo-full.html
test/basic.html
test/index.html
yarn.lock

fixes https://github.com/Neovici/cosmoz-grouped-list/issues/14
fixes codeclimate duplication issues.

Const instead of let and other code optimizations

---

analysis.json
cosmoz-grouped-list-template-selector.html
cosmoz-grouped-list-templatize-behavior.html
cosmoz-grouped-list.html
cosmoz-grouped-list.js
demo/helpers/demo-basic.html
demo/helpers/demo-full.html
package-lock.json
package.json
test/basic.html
yarn.lock

Refactor templatize usage
Updated deps
Moved templatize parts to its own behavior

templatize improvements

---

bower.json
cosmoz-grouped-list-template-selector.html
cosmoz-grouped-list-templatize-behavior.html
cosmoz-grouped-list.js
demo/helpers/demo-full.html
wct.conf.json
yarn.lock

Rebase dropdown fix and misc tweaks

Rebase dropdown fix and misc tweaks

---

cosmoz-grouped-list.js

Fixes selectAll,deselectAll forwarding (flush)

Fix selectAll, deselectAll forwarding (flush)

---

cosmoz-grouped-list-template-selector.html
cosmoz-grouped-list-templatize-behavior.html
cosmoz-grouped-list.js
package-lock.json
package.json
test/basic.html
yarn.lock

Fix templates reuse performance and don't flush properties on initial `getInstance` if item is null.

Fix templates reuse performance

---

.travis.yml
analysis.json
bower.json
cosmoz-grouped-list-template-selector.html
cosmoz-grouped-list-templatize-behavior.html
cosmoz-grouped-list.js
package-lock.json
package.json
polymer.json
test/basic.html
yarn.lock

Support 2.x only

---

cosmoz-grouped-list.js

Fixes shaddy DOM attach and slot assignment

Fixes shaddy DOM attach and slot assignment

---

cosmoz-grouped-list.js

Update to Polymer 2.x - part 2.
* Updated to ES6 class syntax.
Issue is #32.

32 - Update to Polymer 2.x - part 2

---

cosmoz-grouped-list-template-selector.html
cosmoz-grouped-list-templatize-behavior.html
cosmoz-grouped-list.js

Update to Polymer 2.x - part 3.
* Adding comments.
Issue is #32.

32 - Update to Polymer 2.x - part 3

---

cosmoz-grouped-list.js

Fixes classList usage in observer
Replace with this.classList

Fixes classList usage in observer

---

cosmoz-grouped-list.js

Fixes lifecycle with `mixinBehaviors`

Fixes lifecycle with mixinBehaviors

---

.eslintignore
.travis.yml
cosmoz-grouped-list-template-selector.html
cosmoz-grouped-list-templatize-behavior.html
cosmoz-grouped-list.html
cosmoz-grouped-list.js
package-lock.json
package.json
test/basic.html
wct.conf.json
yarn.lock

[2.x] Upgrade to 2.x class-based

---

cosmoz-grouped-list.js

Fixes scrollTarget observer

---

cosmoz-grouped-list.js
test/basic.html

(patch) Removing a selected item clears selection

---

demo/helpers/demo-basic.html

(dev) basic demo fails because "data must be homogeneous"

---

demo/helpers/demo-basic.html
demo/helpers/demo-full.html
demo/helpers/demo-list-behavior.html
demo/helpers/demo-list-helper.html

Demo, converting views to class-style.
Testing: `yarn install; yarn start`, go to `http://127.0.0.1:<your port>/components/cosmoz-grouped-list/demo/` where `<your port>` can be `8000` or something else.
Build errors are due to the Chrome 74-76 error.
Issue is https://github.com/Neovici/cosmoz-frontend/issues/815.

Demo, converting views to class-style

---

demo/helpers/demo-full.js

https://github.com/Neovici/cosmoz-frontend/issues/1314

(patch) modulizer erroneously escaped `attr$=` to `attr\$=`

---

cosmoz-grouped-list.js
test/basic.html
test/index.html

Re https://neovici.slack.com/archives/C6LJQMJFM/p1569564794025400
Re https://github.com/Neovici/cosmoz-frontend/pull/1562

(patch) selection is not cleared when selected items are removed from the dataset

---

cosmoz-grouped-list.js
test/basic.html

Add ability to define comparison function used when determining which items should be selected after a data update.
Todo:

feat(selected): customize maintain selection behavior

---

cosmoz-grouped-list-row.js
demo/helpers/demo-full.js
package-lock.json
use-cosmoz-grouped-list.js
utils.js

DId some changes to the iron-list fork to work around some performance issues.

fix: iron-list performance issues

---

package-lock.json
package.json
use-cosmoz-grouped-list.js

BREAKING CHANGE: Upgrade to lit@^2 and haunted@^5

feat: upgrade to lit@^2

---

.github/workflows/workflow.yml
cosmoz-grouped-list.js
package-lock.json
package.json
use-collapsible-items.js
use-cosmoz-grouped-list.js
use-selected-items.js
use-weak-state.js

BREAKING CHANGE: Update to @pionjs/pion

feat: update to pion

---

package-lock.json
package.json
test/basic.test.js
use-collapsible-items.js
use-cosmoz-grouped-list.js

BREAKING CHANGE: drop polymer iron-list
BREAKING CHANGE: drop updateSize and scrollTarget

feat!: upgrade to lit-virtualizer
